# Generated by Django 5.2.8 on 2026-04-04 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_order_assigned_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='logistics.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
