# Generated by Django 5.2.8 on 2026-04-04 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_order_assigned_vehicle_vehicle_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='service_time_sec',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='time_window_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='time_window_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(default='pcs', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='time_window_end',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='time_window_start',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cost_per_km',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='end_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ending_vehicles', to='logistics.location'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='start_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starting_vehicles', to='logistics.location'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='weight_capacity',
            field=models.FloatField(default=1000.0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('warehouse', 'Warehouse / Depot'), ('supplier', 'Supplier / Pickup'), ('customer', 'Customer / Delivery'), ('hotspot', 'Priority Hotspot')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vehicles', to='logistics.location'),
        ),
    ]
